
export const CONSTANTS = {
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
    MIN_PAGE_SIZE: 10
  },
  TIMEOUTS: {
    DEFAULT_TIMEOUT: 5000,
    MAX_RETRIES: 3,
    RETRY_DELAY: 1000
  },
  VALIDATION: {
    MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
    MAX_STRING_LENGTH: 1000,
    MIN_PASSWORD_LENGTH: 8
  }
};